Update buildami.yaml

diff --git a/.github/workflows/buildami.yaml b/.github/workflows/buildami.yaml
--- a/.github/workflows/buildami.yaml
+++ b/.github/workflows/buildami.yaml
@@ -68,10 +68,40 @@ jobs:
           aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
           aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
           aws configure set region ${{ secrets.AWS_REGION_DEMO}}
-      
-      - name: Create New Version of Launch Template
+
+      - name: Instance Refresh automation / Continuous Delivery 
         run: |
-          AMI_ID=${{ env.AMI_ID }}
-          aws ec2 modify-launch-template \
-           --launch-template-name webAppLaunchTemplate \
-           --default-version $AMI_ID
+          sudo apt-get install jq
+          ASG_NAME=webAppAutoScalingGroup
+          LAUNCH_CONFIG=webAppLaunchTemplate
+          IMAGE=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d':' -f2)
+          IMAGE_ID=$(jq -n \
+            --arg img "$IMAGE" \
+            '{"ImageId": $img}')
+          aws ec2 create-launch-template-version \
+            --launch-template-name "$LAUNCH_CONFIG" \
+            --version-description updateAMI --source-version 1 \
+            --launch-template-data="$IMAGE_ID"
+          TEMPLATE_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-name="$LAUNCH_CONFIG" \
+            --filters="Name=is-default-version,Values=false" \
+            --query 'sort_by(LaunchTemplateVersions, &CreateTime)[-1].[VersionNumber]' --output text)
+          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME \
+            --launch-template LaunchTemplateName="$LAUNCH_CONFIG",Version=$TEMPLATE_VERSION
+          aws autoscaling start-instance-refresh \
+            --auto-scaling-group-name $ASG_NAME --strategy Rolling
+          printf "Instance refresh in progress"
+          while true;
+          do
+            instance_refresh_status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME \
+              --query "InstanceRefreshes[0].Status" --output text)
+            if [ "$instance_refresh_status" = "Successful" ]; then
+              printf "\nInstance refresh successful!"
+              break
+            fi
+            if [ "$instance_refresh_status" = "Cancelling" ] || [ "$instance_refresh_status" = "Cancelled" ] || [ "$instance_refresh_status" = "Failed" ]; then
+              printf "\nInstance refresh failed!"
+              exit 1
+            fi
+            echo -ne "."
+            sleep 10
+          done
